### ISSUE TITLE
'on_delete'

### ISSUE THREAD

**Issue by testori** [chapkovski/fehr-and-gaechter#1]
Dear Philip,
Thank you very much for making this code available. It is very very useful!
I have a little issue: I have installed the new django version and now I have an error:

  File "/Users/IT_PGG/pggfg/models.py", line 200, in <module>
    class Punishment(djmodels.Model):
  File "/Users/T_PGG/pggfg/models.py", line 201, in Punishment
    sender = djmodels.ForeignKey(to=Player, related_name='punishments_sent')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

I tried by including on_delete=models.CASCADE in both djmodels.ForeignKey bur this new error message appears:

ERROR Internal Server Error: /
Internal Server Error: /
ERROR Internal Server Error: /
ERROR Internal Server Error: /favicon.ico
Internal Server Error: /favicon.ico
ERROR Internal Server Error: /favicon.ico
ERROR Internal Server Error: /

Is there any chance you know how to solve this issue?
Thank you very much for your time and your amazing job!

**Comment by chapkovski** [comment]
so, you solved it?

**Comment by testori** [comment]
Yes sorry, I think I just managed, sorry for bothering you!!
